### ISSUE TITLE
Npm package monitoring

### ISSUE THREAD

**Issue by jeroenpg** [ito-org/ito-app#107]
There is currently no tooling in the ci pipeline that checks for vulnerabilties in the dependencies. As far as I know there are two available tools out there, snyk.io and npm audit, that can do this for us. Snyk.io seems to support golang as well. I think this could be worth integrating, what do you think?

**Links**
Comparison: https://www.nearform.com/blog/comparing-npm-audit-with-snyk/
Snyk: https://snyk.io
Npm audit: https://docs.npmjs.com/cli/audit

**Comment by haveyaseen** [comment]
Certainly, sounds like a great idea!

**Comment by ChristianRomberg** [comment]
I think github does something like that with the dependabot?

**Comment by assert-not-singularity** [comment]
> I think github does something like that with the dependabot?

Afaik, the depandabot just issues Pull Requests when a new version of a library or some other dependency is released.

Under Options > Data Services there should be an option to turn on security alerts for this repo.

**Comment by Dionysusnu** [comment]
They are enabled by default. They were integrated into GitHub, but I think they've now rebranded it as a dependabot feature.

**Comment by haveyaseen** [comment]
I enabled Snyk and it's currently reporting 1 issue that GitHub is not reporting. Also the automatic security fixes by GitHub have never worked for me. Snyk checks for security issues with new PRs. And we will see if it sends another PR. Then we may want to reconsider enabling Snyk.

**Comment by haveyaseen** [comment]
Snyk is active. Remaining issue: #184
